import type { Media } from "@/types"


export const movieData: Media[] = [
    {
        "id": 1,
        "title": "The Dark Knight",
        "image": "https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=400&h=600&fit=crop",
        "largePoster": "https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=800&h=1200&fit=crop",
        "synopsis": "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
        "rentPrice": 3.99,
        "purchasePrice": 14.99,
        "year": 2008,
        "genre": "Action, Crime, Drama",
        "mediaType": "movie",
        "featured": false
    },
    {
        "id": 2,
        "title": "Avengers: Endgame",
        "image": "https://images.unsplash.com/photo-1635805737707-575885ab0820?w=400&h=600&fit=crop",
        "largePoster": "https://images.unsplash.com/photo-1635805737707-575885ab0820?w=800&h=1200&fit=crop",
        "synopsis": "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more.",
        "rentPrice": 4.99,
        "purchasePrice": 19.99,
        "year": 2019,
        "genre": "Action, Adventure, Drama",
        "mediaType": "movie",
        "featured": false
    },
    {
        "id": 3,
        "title": "Inception",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSevUsx9JAl2R48BU7n6XeQUlD4NOB3frvjdQ&s",
        "largePoster": "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/a447f0f0-8834-4538-8519-2ee6de0d4e02/d6c2i5v-49dd2355-5ead-4d2c-8831-9e4b674bb1be.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2E0NDdmMGYwLTg4MzQtNDUzOC04NTE5LTJlZTZkZTBkNGUwMlwvZDZjMmk1di00OWRkMjM1NS01ZWFkLTRkMmMtODgzMS05ZTRiNjc0YmIxYmUuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.OfOsMC6pIEoZ9ylhOAMkJT6NxM8VSmDwXnuifCBkWaE",
        "synopsis": "Dom Cobb is a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets.",
        "rentPrice": 3.99,
        "purchasePrice": 12.99,
        "year": 2010,
        "genre": "Action, Sci-Fi, Thriller",
        "mediaType": "movie",
        "featured": false
    },
    {
        "id": 4,
        "title": "Spider-Man: No Way Home",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnNUuluFOjwPn8Lt5IK0pQ0Uw2ZDVe5a8HkA&s",
        "largePoster": "https://live.staticflickr.com/65535/51725408655_394ff30d84_b.jpg",
        "synopsis": "Spider-Man's identity is revealed to the entire world. Desperate for help, Peter turns to Doctor Strange.",
        "rentPrice": 5.99,
        "purchasePrice": 24.99,
        "year": 2021,
        "genre": "Action, Adventure, Fantasy",
        "mediaType": "movie",
        "featured": false
    },
    {
        "id": 5,
        "title": "Top Gun: Maverick",
        "image": "https://images.unsplash.com/photo-1474631245212-32dc3c8310c6?w=400&h=600&fit=crop",
        "largePoster": "https://images.unsplash.com/photo-1474631245212-32dc3c8310c6?w=800&h=1200&fit=crop",
        "synopsis": "After thirty years, Maverick is still pushing the envelope as a top naval aviator, training a new generation.",
        "rentPrice": 4.99,
        "purchasePrice": 19.99,
        "year": 2022,
        "genre": "Action, Drama",
        "mediaType": "movie",
        "featured": false
    },
    {
        "id": 6,
        "title": "Dune",
        "image": "https://images.unsplash.com/photo-1446776653964-20c1d3a81b06?w=400&h=600&fit=crop",
        "largePoster": "https://images.unsplash.com/photo-1446776653964-20c1d3a81b06?w=800&h=1200&fit=crop",
        "synopsis": "Paul Atreides leads nomadic tribes in a fight against the enemies of the desert planet Arrakis.",
        "rentPrice": 4.99,
        "purchasePrice": 17.99,
        "year": 2021,
        "genre": "Action, Adventure, Drama",
        "mediaType": "movie",
        "featured": false
    },
    {
        "id": 7,
        "title": "The Matrix Resurrections",
        "image": "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=400&h=600&fit=crop",
        "largePoster": "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=800&h=1200&fit=crop",
        "synopsis": "Neo lives a seemingly ordinary life as Thomas Anderson until he is offered a chance to wake up from the Matrix once again.",
        "rentPrice": 3.99,
        "purchasePrice": 16.99,
        "year": 2021,
        "genre": "Action, Sci-Fi",
        "mediaType": "movie",
        "featured": false
    },
    {
        "id": 8,
        "title": "Black Widow",
        "image": "https://images.unsplash.com/photo-1512070679279-8988d32161be?w=400&h=600&fit=crop",
        "largePoster": "https://images.unsplash.com/photo-1512070679279-8988d32161be?w=800&h=1200&fit=crop",
        "synopsis": "Natasha Romanoff confronts the darker parts of her ledger when a dangerous conspiracy ties to her past.",
        "rentPrice": 3.99,
        "purchasePrice": 14.99,
        "year": 2021,
        "genre": "Action, Adventure, Sci-Fi",
        "mediaType": "movie",
        "featured": false
    },
    {
        "id": 9,
        "title": "No Time to Die",
        "image": "https://img.goodfon.com/original/5120x2880/c/4f/no-time-to-die-daniel-craig-007-deniel-kreig.jpg",
        "largePoster": "https://cdn.printerval.com/unsafe/960x960/asset/11561d0c0b010b0c190c111b561b1715574b414b404d40414c570a571114574948484d484e574c4c4e4f48414149494c571114271e0d1414001e0d1414564c4c4e4f48414149494c274e4f491c5612081f",
        "synopsis": "James Bond has left active service. His peace is short-lived when Felix Leiter asks for help finding a kidnapped scientist.",
        "rentPrice": 4.99,
        "purchasePrice": 18.99,
        "year": 2021,
        "genre": "Action, Adventure, Thriller",
        "mediaType": "movie",
        "featured": false
    },
    {
        "id": 10,
        "title": "Fast & Furious 9",
        "image": "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=400&h=600&fit=crop",
        "largePoster": "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800&h=1200&fit=crop",
        "synopsis": "Dom Toretto and his family face their most lethal adversary: a skilled assassin, high-performance driver, and Dom's forsaken brother.",
        "rentPrice": 3.99,
        "purchasePrice": 15.99,
        "year": 2021,
        "genre": "Action, Crime, Thriller",
        "mediaType": "movie",
        "featured": false
    },
    {
        "id": 11,
        "title": "Wonder Woman 1984",
        "image": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=600&fit=crop",
        "largePoster": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=1200&fit=crop",
        "synopsis": "Diana Prince comes into conflict with the Soviet Union during the Cold War in the 1980s.",
        "rentPrice": 3.99,
        "purchasePrice": 14.99,
        "year": 2020,
        "genre": "Action, Adventure, Fantasy",
        "mediaType": "movie",
        "featured": false
    },
    {
        "id": 12,
        "title": "Tenet",
        "image": "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=400&h=600&fit=crop",
        "largePoster": "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=800&h=1200&fit=crop",
        "synopsis": "Armed with only one word, Tenet, and fighting for the survival of the entire world, the Protagonist journeys through a twilight world.",
        "rentPrice": 4.99,
        "purchasePrice": 17.99,
        "year": 2020,
        "genre": "Action, Sci-Fi, Thriller",
        "mediaType": "movie",
        "featured": false
    }
]

export const tvShowData: Media[] = [
    {
        "id": 1,
        "title": "Breaking Bad",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnlVJuAOlwJYbfmSdpVvgQCoyoh6VRwN43mg&s",
        "largePoster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkR183yuSei7UmML_9uLykwVbz_vg9GsUR5w&s",
        "synopsis": "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine.",
        "rentPrice": 2.99,
        "purchasePrice": 39.99,
        "year": 2008,
        "genre": "Crime, Drama, Thriller",
        "mediaType": "tvshow",
        "featured": false
    },
    {
        "id": 2,
        "title": "Game of Thrones",
        "image": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=600&fit=crop",
        "largePoster": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=1200&fit=crop",
        "synopsis": "Nine noble families wage war against each other in order to gain control over the mythical land of Westeros.",
        "rentPrice": 3.99,
        "purchasePrice": 49.99,
        "year": 2011,
        "genre": "Action, Adventure, Drama",
        "mediaType": "tvshow",
        "featured": false
    },
    {
        "id": 3,
        "title": "Stranger Things",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNt9Agi9nyVSdtuOtIZZ8pq-mEavcz5nfpIA&s",
        "largePoster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5aeYaxyF-GPaj4FHBuDI7LrjRdPzY2uqL7Q&s",
        "synopsis": "When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces.",
        "rentPrice": 2.99,
        "purchasePrice": 34.99,
        "year": 2016,
        "genre": "Drama, Fantasy, Horror",
        "mediaType": "tvshow",
        "featured": false
    },
    {
        "id": 4,
        "title": "The Mandalorian",
        "image": "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=600&fit=crop",
        "largePoster": "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=1200&fit=crop",
        "synopsis": "The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.",
        "rentPrice": 3.99,
        "purchasePrice": 29.99,
        "year": 2019,
        "genre": "Action, Adventure, Fantasy",
        "mediaType": "tvshow",
        "featured": false
    },
    {
        "id": 5,
        "title": "The Crown",
        "image": "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=600&fit=crop",
        "largePoster": "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=1200&fit=crop",
        "synopsis": "Follows the political rivalries and romance of Queen Elizabeth II's reign and the events that shaped the second half of the 20th century.",
        "rentPrice": 2.99,
        "purchasePrice": 39.99,
        "year": 2016,
        "genre": "Biography, Drama, History",
        "mediaType": "tvshow",
        "featured": false
    },
    {
        "id": 6,
        "title": "The Witcher",
        "image": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=600&fit=crop",
        "largePoster": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=1200&fit=crop",
        "synopsis": "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.",
        "rentPrice": 3.99,
        "purchasePrice": 27.99,
        "year": 2019,
        "genre": "Action, Adventure, Drama",
        "mediaType": "tvshow",
        "featured": false
    },
    {
        "id": 7,
        "title": "Ozark",
        "image": "https://live.staticflickr.com/4829/46771503322_169f7d54b9_b.jpg",
        "largePoster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmX4bpDIMNObspKjZkdlBm6uwpkJDnIdbxMQ&s",
        "synopsis": "A financial advisor drags his family to the Missouri Ozarks, where he must launder money to appease a drug boss.",
        "rentPrice": 2.99,
        "purchasePrice": 32.99,
        "year": 2017,
        "genre": "Crime, Drama, Thriller",
        "mediaType": "tvshow",
        "featured": false
    },
    {
        "id": 8,
        "title": "House of Cards",
        "image": "https://i2.pickpik.com/photos/926/405/240/house-of-cards-fragile-patience-sensitive-preview.jpg",
        "largePoster": "https://live.staticflickr.com/40/84452168_fa5f7e263a_c.jpg",
        "synopsis": "A Congressman works with his equally conniving wife to exact revenge on the people who betrayed him.",
        "rentPrice": 2.99,
        "purchasePrice": 35.99,
        "year": 2013,
        "genre": "Drama",
        "mediaType": "tvshow",
        "featured": false
    },
    {
        "id": 9,
        "title": "The Boys",
        "image": "https://images.unsplash.com/photo-1635805737707-575885ab0820?w=400&h=600&fit=crop",
        "largePoster": "https://images.unsplash.com/photo-1635805737707-575885ab0820?w=800&h=1200&fit=crop",
        "synopsis": "A group of vigilantes set out to take down corrupt superheroes with no more than blue collar grit and a willingness to fight dirty.",
        "rentPrice": 3.99,
        "purchasePrice": 28.99,
        "year": 2019,
        "genre": "Action, Comedy, Crime",
        "mediaType": "tvshow",
        "featured": false
    },
    {
        "id": 10,
        "title": "Money Heist",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPkshawbuDgEfQfYRN23rpq-LJz-uhCVCJUg&s",
        "largePoster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQr5n-CLCwRqDUjLaoAraAtHxCwH0qfNc-OlQ&s",
        "synopsis": "An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.",
        "rentPrice": 2.99,
        "purchasePrice": 31.99,
        "year": 2017,
        "genre": "Action, Crime, Mystery",
        "mediaType": "tvshow",
        "featured": false
    },
    {
        "id": 11,
        "title": "Squid Game",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYysDw3p5oWD5Jmk6qeHnBYYfOdeaMxkVIQg&s",
        "largePoster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3zcXt01J19lLwZw1UbXSztNgBzHFb06htoQ&s",
        "synopsis": "Hundreds of cash-strapped players accept a strange invitation to compete in children's games for a tempting prize.",
        "rentPrice": 3.99,
        "purchasePrice": 25.99,
        "year": 2021,
        "genre": "Action, Drama, Mystery",
        "mediaType": "tvshow",
        "featured": false
    },
    {
        "id": 12,
        "title": "Bridgerton",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReOJrO5Z5MVRLLzvB__uanXATIi0apoHCewg&s",
        "largePoster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeW2TTW7CsobpZhzC9m4ikBBkiDQKKfnS9LQ&s",
        "synopsis": "Wealth, lust, and betrayal set in the backdrop of Regency era England, seen through the eyes of the powerful Bridgerton family.",
        "rentPrice": 2.99,
        "purchasePrice": 29.99,
        "year": 2020,
        "genre": "Drama, Romance",
        "mediaType": "tvshow",
        "featured": false
    }
]

export const heroMovieData: Media[] = [
    {
        "id": 1,
        "title": "The Dark Knight",
        "image": "https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=800&h=450&fit=crop",
        "largePoster": "https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=1600&h=900&fit=crop",
        "synopsis": "Batman faces his greatest challenge yet when the Joker wreaks havoc on Gotham City.",
        "rentPrice": 3.99,
        "purchasePrice": 14.99,
        "year": 2008,
        "genre": "Action, Crime, Drama",
        "mediaType": "movie",
        "featured": true,
        "description": "Batman faces his greatest challenge yet when the Joker wreaks havoc on Gotham City."
    },
    {
        "id": 2,
        "title": "Avengers: Endgame",
        "image": "https://images.unsplash.com/photo-1635805737707-575885ab0820?w=800&h=450&fit=crop",
        "largePoster": "https://images.unsplash.com/photo-1635805737707-575885ab0820?w=1600&h=900&fit=crop",
        "synopsis": "The Avengers assemble one final time to reverse the destruction caused by Thanos.",
        "rentPrice": 3.99,
        "purchasePrice": 14.99,
        "year": 2019,
        "genre": "Action, Adventure, Drama",
        "mediaType": "movie",
        "featured": true,
        "description": "The Avengers assemble one final time to reverse the destruction caused by Thanos."
    },
    {
        "id": 3,
        "title": "Inception",
        "image": "https://static01.nyt.com/images/2010/07/25/arts/25scott-span/25scott-span-articleLarge.jpg?quality=75&auto=webp&disable=upscale",
        "largePoster": "https://static01.nyt.com/images/2010/07/25/arts/25scott-span/25scott-span-articleLarge.jpg?quality=75&auto=webp&disable=upscale",
        "synopsis": "A mind-bending thriller about dreams within dreams.",
        "rentPrice": 3.99,
        "purchasePrice": 14.99,
        "year": 2010,
        "genre": "Action, Sci-Fi, Thriller",
        "mediaType": "movie",
        "featured": true,
        "description": "A mind-bending thriller about dreams within dreams."
    },
    {
        "id": 4,
        "title": "Spider-Man: No Way Home",
        "image": "https://www.rollingstone.com/wp-content/uploads/2021/12/SpiderManFFH.jpg?w=1581&h=1054&crop=1",
        "largePoster": "https://www.rollingstone.com/wp-content/uploads/2021/12/SpiderManFFH.jpg?w=1581&h=1054&crop=1",
        "synopsis": "Spider-Man's identity is revealed, bringing chaos to his life.",
        "rentPrice": 3.99,
        "purchasePrice": 14.99,
        "year": 2021,
        "genre": "Action, Adventure, Fantasy",
        "mediaType": "movie",
        "featured": true,
        "description": "Spider-Man's identity is revealed, bringing chaos to his life."
    },
    {
        "id": 5,
        "title": "Top Gun: Maverick",
        "image": "https://images.unsplash.com/photo-1474631245212-32dc3c8310c6?w=800&h=450&fit=crop",
        "largePoster": "https://images.unsplash.com/photo-1474631245212-32dc3c8310c6?w=1600&h=900&fit=crop",
        "synopsis": "Maverick returns to train a new generation of pilots.",
        "rentPrice": 3.99,
        "purchasePrice": 14.99,
        "year": 2022,
        "genre": "Action, Drama",
        "mediaType": "movie",
        "featured": true,
        "description": "Maverick returns to train a new generation of pilots."
    },
    {
        "id": 6,
        "title": "Dune",
        "image": "https://images.unsplash.com/photo-1446776653964-20c1d3a81b06?w=800&h=450&fit=crop",
        "largePoster": "https://images.unsplash.com/photo-1446776653964-20c1d3a81b06?w=1600&h=900&fit=crop",
        "synopsis": "A young man's journey on a desert planet that holds the key to the future.",
        "rentPrice": 3.99,
        "purchasePrice": 14.99,
        "year": 2021,
        "genre": "Action, Adventure, Drama",
        "mediaType": "movie",
        "featured": true,
        "description": "A young man's journey on a desert planet that holds the key to the future."
    },
    {
        "id": 7,
        "title": "The Matrix Resurrections",
        "image": "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=800&h=450&fit=crop",
        "largePoster": "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=1600&h=900&fit=crop",
        "synopsis": "Neo returns to the Matrix in this mind-bending sequel.",
        "rentPrice": 3.99,
        "purchasePrice": 14.99,
        "year": 2021,
        "genre": "Action, Sci-Fi",
        "mediaType": "movie",
        "featured": true,
        "description": "Neo returns to the Matrix in this mind-bending sequel."
    },
    {
        "id": 8,
        "title": "Black Widow",
        "image": "https://cdn.hswstatic.com/gif/black-widow-1.jpg",
        "largePoster": "https://cdn.hswstatic.com/gif/black-widow-1.jpg",
        "synopsis": "Natasha Romanoff confronts her past as a spy.",
        "rentPrice": 3.99,
        "purchasePrice": 14.99,
        "year": 2021,
        "genre": "Action, Adventure, Sci-Fi",
        "mediaType": "movie",
        "featured": true,
        "description": "Natasha Romanoff confronts her past as a spy."
    },
    {
        "id": 9,
        "title": "No Time to Die",
        "image": "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/d77c3a7f-0780-4a0e-b61f-5de00c06adb8/de0eyj1-c40e506a-b34f-4301-ae13-eb849e57e8e7.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2Q3N2MzYTdmLTA3ODAtNGEwZS1iNjFmLTVkZTAwYzA2YWRiOFwvZGUwZXlqMS1jNDBlNTA2YS1iMzRmLTQzMDEtYWUxMy1lYjg0OWU1N2U4ZTcucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.l3HBVSn9wOLA2RTgYg36uJtmxUhXHFaxDXENs8sV0f4",
        "largePoster": "https://images.wikia.nocookie.net/jamesbond/images/5/5f/No_Time_to_Die_poster.jpg",
        "synopsis": "James Bond's final mission in this thrilling conclusion.",
        "rentPrice": 3.99,
        "purchasePrice": 14.99,
        "year": 2021,
        "genre": "Action, Adventure, Thriller",
        "mediaType": "movie",
        "featured": true,
        "description": "James Bond's final mission in this thrilling conclusion."
    }
]